version: '3.8'
services:
  api-student-29:
    build: .
    ports:
      - "3029:3000"
    environment:
      DB_URL: mongodb://mongo-student-29:27046/CRMdb-student-29
      PORT: 3000
    depends_on:
      - mongo-student-29
  mongo-student-33:
    image: mongo:latest
    ports:
      - "27050:27046"
    volumes:
      - db-data-student-29:/data/db
volumes:
  db-data-student-29:
