version: "3.8"
services:
  app:
    build: .
    ports:
      - "3029:3000"
    environment:
      - DB_URL=mongodb://mongo:27017/CRMdb
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  mongo:
    image: mongo
    ports:
      - "27046:27017"
    volumes:
      - mongo-data:/data/db

  monitoring:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  mongo-data:
